config/routes.rb
Rails.application.routes.draw do

  root to: "static_pages#root"
  resources :users, except: [:show, :index]
  get 'home', to: 'static_pages#home'
  resource :sessions

  namespace :api, defaults: {:format => :json} do 
    resources :users, only: [:show, :index, :edit, :update]
    resources :posts
    resources :comments, only: [:create, :destroy, :new]	
    resources :maps
  end
  
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	validates :user_id, :content, presence: true 
	belongs_to :user 
	belongs_to :post
	
end

app/models/map.rb
class Map < ActiveRecord::Base
	validates :user_id, :total_miles, :elevations, :path, presence: true
	belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
	validates :user_id, :workout_type, presence: true	
	belongs_to :user
	has_many :comments
	before_destroy :confirm_user

	def confirm_user 
		unless current_user.id == self.user_id 
			errors.add_to_base "you can't delete another user's activity"
			return false
		end
	end
end

app/models/user.rb
class User < ActiveRecord::Base
	validates :username, :password_digest, presence: true
	validates :username, uniqueness: true
	validates :password, length: { minimum: 6, allow_nil: true }
	after_initialize :ensure_session_token
	attr_accessor :password
	
	has_many :posts
	has_many :maps

	def password=(password)
		@password = password
		self.password_digest = BCrypt::Password.create(password)
		@password
	end

	def reset_session_token 
		self.session_token = SecureRandom.urlsafe_base64
		self.save!
		self.session_token
	end

	def self.find_by_credentials(username, password) 
		user = User.find_by_username(username)
		p user
		if !user
			return nil
		end
		user.valid_password?(password) ? user : nil
	end

	def valid_password?(password)
	 	BCrypt::Password.new(self.password_digest).is_password?(password);
	end

	private 

		def ensure_session_token 
			self.session_token ||= SecureRandom.urlsafe_base64
		end

end

app/controllers/api/comments_controller.rb
module Api
	class CommentsController < ApplicationController
		def create
			@comment = Comment.new(comment_params)
			if @comment.save
				render "users/show"
			end
		end

		def edit
			@comment = Comment.find(params[:id])			
		end

		def new
			@comment = Comment.new
		end

		def update 
			@comment = Comment.find(params[:id])
			if @comment.update!(comment_params)
				render "users/show"
			end
		end

		private 

		def comment_params
			param.require(:commnt).permit(:id, :content, :user_id)
		end
	end
end

app/controllers/api/maps_controller.rb
module Api
	class MapsController < ApplicationController
		def new 
		end

		def create 
			@map = Map.new(map_params)
			@map.user_id = current_user.id
			@map.name = "map"
			
			if @map.save
				render :new
			end
		end

		def show 
			@map = Map.find(params[:id])
		end 

		def map_params
			params.require(:map).permit(:path, :total_miles, :name, :elevations, :markers, :elevation_gain, :calories, :minutes, :heart_rate)
		end

	end
end

app/controllers/api/posts_controller.rb
module Api
	class PostsController < ApplicationController
		def create 
			@post = Post.new(post_params)
			@post.user_id = current_user.id
			if @post.save
				redirect_to root_url
			else
				render "users/show"
			end
		end

		def index
			@posts = Post.includes(:comments).all
		end

		def new 
			@post = Post.new()
		end

		def destroy 
			@post = Post.includes(:comments).find.(params[:id])
			@user = current_user
			@posts = @user.posts
			if @post.delete
				render "users/show"
			else
				render "users/show"
			end
		end

		private 

			def post_params 
				params.require(:post).permit(:user_id, :workout_type, :heart_rate, :minutes, :calories)
			end
	end

end

app/controllers/api/users_controller.rb
	module Api
		class UsersController < ApplicationController
			def show 
				redirect_to new_sessions_url unless current_user
				User.includes(:maps, :posts)
				@user = User.find(params[:id])
				@posts = @user.posts.includes(:comments)
				render "show"	
			end

			def index 
				@users = User.page(params[:page]).per(5)
				@page = params[:page]
				render "index"
			end

			def update 
				User.includes(:maps, :posts)
				@user = User.find(params[:id])
				@posts = @user.posts
				if params[:old_password]
					if !@user.valid_password?(params[:old_password])
						flash.now[:errors] = ["You're password is incorrect"]
						render "show"
					else
						@user.password_digest = BCrypt::Password.create(params[:new_password])
						render "show"
					end
				else
					if @user.update!(user_params)
						render "show"
					else 
						flash.now[:errors] = @user.errors.full_messages
						render "show"
					end
				end
			end

			def edit 
				User.includes(:maps, :posts)
				@user = User.find(params[:id])
			end

			private 
			def user_params
				params.require(:user).permit(
					:id,
					:username, 
					:age, 
					:weight, 
					:gender, 
					:height,
					:city,
					:state
				)
			end
		end

	end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :twilio, :send_message

  def current_user 
  	User.find_by_session_token(session[:token]);
  end

  def twilio
    # To find these visit https://www.twilio.com/user/account
    #require 'twilio-ruby'
    #account_sid = "ACa10aec94c8d1c2a0f157b7639ca373b5"
    #auth_token = "7680119fffc4c651147e7db465d8cdbc"
    #Twilio::REST::Client.new account_sid, auth_token
  end

  def send_message(message, number, client)
    #@message = client.account.messages.create({:to => number,
    #                               :from => "+16503895324",
    #                               :body => message})
  end

  def log_in!(user)
  	session[:token] = user.session_token 
  end

  def log_out!(user)
  	session[:token] = nil
  	user.reset_session_token
  end

end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new 
    @user = User.new
  end

  def create 
    @user = User.find_by_credentials(params[:user][:username], params[:user][:password])
    if @user.nil?
      flash.now[:errors] = ["We could not process your request."]
      render :new
    else 
      log_in!(@user)
      redirect_to root_url
    end
  end

  def destroy
    if current_user.nil? 
      redirect_to root_url
    else 
      log_out!(current_user)
      redirect_to new_sessions_url
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def root
  	redirect_to home_url unless current_user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new 
  	render :new 
  end

  def create 
  	@user = User.new(user_params)
    
  	if @user.save 
  		log_in!(@user)

      if @user.phone_number 
        @client = twilio
        send_message("Hello! Welcome to TrakMyRun", @user.phone_number, @client)
      end
      
  		redirect_to root_url
  	else 
  		flash.now[:errors] = @user.errors.full_messages
  		render :new
  	end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = ["Request completed"]
      redirect_to :root
    end
  end

  def destroy 
  end

  private

  def user_params 
  	params.require(:users).permit(:username, :password, :image_url, :email, :phone_number)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_auth_header.html.erb
<div class="row">
  <nav class="navbar navbar-inverse" role="navigation">
    <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/home">TrakMyRun</a>
      </div>


      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Sign In", new_sessions_url%></li>
        <li><%= link_to "Sign Up", new_user_url%></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </nav>
</div>

app/views/layouts/_errors.html.erb
<% if flash[:errors] %> 
	<ul class="alert"> 
		<% flash[:errors].each do |error| %>
		<li>&#42 <%= error %> </li>
		<% end %> 
	</ul>
<% end %>

app/views/layouts/_file_upload.html.erb
<form action="/users" method="post">
	<input type="filepicker" name="use[image_url]">
	<input type="submit">
</form>

app/views/layouts/_header.html.erb
<% if current_user %>
  <nav class="navbar navbar-inverse" role="navigation">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#users/<%=current_user.id%>">TrakMyRun</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li class="active">
            <a href="#users/<%=current_user.id%>" class="show-icon">
              Home
            </a>
          </li>
         <li>
          <a href="#users">
            <span class="glyphicon glyphicon-flash icon-hover"></span>
            The hub
          </a>
        </li>
          
          <li>
            <a href="#users/<%=current_user.id%>/routes/show" class="show-icon">
              <span class="glyphicon glyphicon-map-marker icon-hover"></span> Create Route
            </a>
          </li>

          <li>
            <a href="#posts/new">
              <span class="glyphicon glyphicon-pencil icon-hover"></span> Log Workout
            </a>
          </li>
          <li>
            <a href="#users/<%=current_user.id%>/dashboard">
              <span class="glyphicon glyphicon-th icon-hover"></span>
              Dashboard
            </a>
          </li>
        </ul>
        <!-- <form class="navbar-form navbar-left" role="search">
          <div class="form-group">
            <input type="text" class="form-control" placeholder="Search">
          </div>
          <button type="submit" class="btn btn-default">Submit</button>
        </form> -->
        <ul class="nav navbar-nav navbar-right">
          <li><a href="#users/<%=current_user.id%>" 
            class="glyphicon glyphicon-home icon-hover blue"></a></li>
          <li><%= link_to "Log Out", sessions_url, method: :delete%></li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

  <!-- IMAGE UPLOAD FORM -->
  <div class="col-md-12 text-center " id="filepicker-form">
    <form class="form col-md-4 col-md-offset-4" action="<%=user_url(current_user)%>" method="post"> 

      <div class="form-group">

        <label for="image"><h1>Upload Image</h1></label> 
        <br>
        <input type="hidden" name="_method" value="PATCH">
        <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>">
        <input type='filepicker' class="form-control" name="users[image_url]">
        <br>
        <div class="row">
          <div class="col-md-6">
            <button class="btn btn-primary form-control">Submit</button>
          </div>

          <div class="col-md-6">
            <button class="btn btn-danger form-control col-md-3 close-form" data-form-id="#filepicker-form">Cancel</button>
          </div>

        </div>
      </div>
    </form>
  </div>

</div>

<% else %>

<% end %>


  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>TrakMyRun</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
  <%= csrf_meta_tags %>
</head>

<body>
  	<%= render "layouts/header" %>
  	<%= yield %>
</body>
	
  <%= javascript_include_tag 'application'%>
	<%= filepicker_js_include_tag %>
	
  <%if current_user %>
  	<script>
  		window.TrakMyRun.CurrentUser = <%= current_user.id %>
  		TrakMyRun.initialize();
  		filepicker.setKey('A4B3VdZ8XT4GGoDJmELANz');
      $(function () {
        $('[data-toggle="tooltip"]').tooltip();
      })
  	</script>
  <% end %>
</html>

app/views/session/new.html.erb
<div class=".container">
<section class="col-md-4 col-md-offset-4 sign-in text-center"> <!--may want to wrap this around yield, just want to get full back pic-->
	<h1 class="text-center">Sign In</h1>
	<%= render :partial => "layouts/errors"%>
	<form action="<%=session_index_url%>" method="post">
		<div class="form-group">
			<label for="username">Username</label>
			<input id="username" placeholder="Username" name="user[username]" class="form-control">
		</div>

		<div class="form-group">
			<label for="password">Password</label>
			<input id="password" placeholder="Password" type="password" name="user[password]" class="form-control">
		</div>

		<input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>">
		<input type="submit" value="Sign In" class="btn btn-default">
	</form>

	<form action="<%=users_url%>" method="post" class="form">
		<input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>">
		<input type="hidden" name="user[username]" value="GuestUser">
		<input type="hidden" name="user[password]" value="guestuser2691">
		<input type="submit" value="Sign In As Guest User" class="btn btn-primary">
	</form>
</section>
</div>

app/views/static_pages/home.html.erb
<%= render 'layouts/auth_header'%>
  <div class="row">
    <div class="logo-banner text-center">
        <h1 class="text-thin logo-text">TrakMyRun</h1>
        <br>
        
    </div>
    <div class="logo-background col-md-4 col-md-offset-4">
    </div>
    <div class="container text-center">
        <a href="<%=new_sessions_url%>" class="col-md-3 col-md-offset-2 visitor-link">Sign In</a>
        <a href="<%=new_user_url%>" class="col-md-3 col-md-offset-2 visitor-link">Sign Up</a>
        </div>
  </div>
  <div class="row">

    <div class="feature-box col-md-4  text-center" id="one">
      <div class="transparent-cover">
        <span class="box-content">Share with friends</span>
      </div>
    </div>

    <div class="feature-box col-md-4  text-center" id="two">
      <div class="transparent-cover">
        <span class="box-content">Reach Goals</span>
      </div>
    </div>

    <div class="feature-box col-md-4  text-center" id="three">
      <div class="transparent-cover">
        <span class="box-content">Discover trails</span>
      </div>
    </div>

<div class="home-background">
  <div class="container">
    <div class="row">
      <h1 class="text-center">Network With Other Runners</h1><hr>
      <div class="col-md-6 text-center feature-icon">
        <img src="assets/network.png">
      </div>
      <div class="feature-description col-md-6">
        TrakMyRun is a social network of runners. Not only can you log your workouts and track your fittness, but you can also share your activities with other athletes as well. Find the competitive athelte within you and try and get the top score for routes by trying your hardest or getting the fastest time.
      </div>
    </div>
    <br>
    <div class="row">
      <h1 class="text-center">Monitor Your Workouts</h1><hr>
      <div class="feature-description col-md-6">
        TrakMyRun comes with a dashboard so that you can see exactly what you have done over time. See how many calories you burned, distance you have ran, how hard you have been working your heart with graphs. You can also switch between months, days, or years.
      </div>
      <div class="col-md-6 text-center feature-icon">
        <img src="assets/icon-performance.png">
      </div>
      
    </div>
    <br>
    <div class="row">
      <h1 class="text-center">Map and Share Your Runs</h1><hr>
      <div class="col-md-6 text-center feature-icon">
        <img src="assets/map.png">
      </div>
      <div class="feature-description col-md-6">
        TrakMyRun comes with a map tool that allows you to plot your runs while also keeping track of elevation and distance. You can load and edit any map that you or your friends have ran by sharing maps with them or joininga group. There are also challenges that happen every once in a while so that you can race to win prizes!
      </div>
    </div>
    <br>

    <br>
  </div>
  <footer>

  </footer>
</div>

app/views/static_pages/root.html.erb
<% if flash[:errors] %> 
<div class="pannel well col-md-6">
	<ul > 
		<%flash[:errors].each do |error| %> 
		<li><%= error %></li>
		<% end %> 
	</ul>
</div>
<% end %>

<div class="container-fluid">
	
	<section class="content">
	</section>

</div>

app/views/users/new.html.erb
<div class="main-background">
	<%= render 'layouts/auth_header' %>
	<div class="container">
			<section class="col-sm-4 col-sm-offset-4 auth-form text-center">
			<h1 class="text-thin">Sign Up</h1>
			<%= render :partial => "layouts/errors"%>
			<form action="<%=users_url%>" method="POST" class="form">
				<div id="required-info">
					<div class="form-group">
						<label for="username" class="text-thin">Username</label>
						<input id="username" placeholder="Username" value="<%=@user.username%>" name="users[username]" class="form-control">
					</div>
					<div class="form-group">
						<label for="password" class="text-thin">Password</label>
						<input id="password" placeholder="Password" type="password" name="users[password]" class="form-control">
					</div>
					<button id="show-contact-info" class="btn btn-primary">Okay</button>
				</div>

				<div id="contact-info">
					<div class="fyi">Enter your contact info to send messages to other runners and recieve messages from groups</div>
					
					<div class="form-group">
						<label for="number" class="text-thin">Number</label>
						<input id="number" placeholder="Phone Number" type="text" name="users[phone_number]" class="form-control">
					</div>

					<div class="form-group">
						<label for="email" class="text-thin">Email</label>
						<input id="email" placeholder="Email" type="email" name="users[email]" class="form-control">
					</div>
					<input type="submit" value="Sign Up" class="btn btn-default">
				</div>
				<input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>">
				
			</form>
			<br>
			<form action="<%=sessions_url%>" method="post" class="form">
				<input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>">
				<input type="hidden" name="users[username]" value="GuestUser">
				<input type="hidden" name="users[password]" value="guestuser2691">
				<input type="hidden" name="users[phone_number]" value="6507738616">
				<input type="hidden" name="users[email]" value="jordanlittell2@gmail.com">
				<input type="submit" value="Sign In As Guest User" class="btn btn-primary">
			</form>
		</section>
	</div>
</div>